import { useState, useRef, useEffect } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import { ZoomIn, ZoomOut, ChevronLeft, ChevronRight, Loader2 } from 'lucide-react';

// Import styles for react-pdf
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';

// Import the worker using Vite's ?url loader to serve it from the same origin
import pdfWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';

// Set worker source to the local URL generated by Vite
pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;

const PdfViewer = ({ url }) => {
  const [numPages, setNumPages] = useState(0);
  const [pageNum, setPageNum] = useState(1);
  const [scale, setScale] = useState(1.0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // State for the text input so it can be edited freely before submitting
  const [pageInputValue, setPageInputValue] = useState("1");
  
  const scrollContainerRef = useRef(null);
  const pageRefs = useRef([]);

  // Callback when document loads successfully
  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
    setLoading(false);
    setPageNum(1);
    setPageInputValue("1");
    setError(null);

    // Reset scroll to top when a new document is loaded
    if (scrollContainerRef.current) {
      scrollContainerRef.current.scrollTop = 0;
    }
  };

  const onDocumentLoadError = (err) => {
    console.error('Error loading PDF:', err);
    setError('Failed to load PDF document. Please verify the URL or your network connection.');
    setLoading(false);
  };

  const handleZoomIn = () => setScale((prev) => Math.min(prev + 0.2, 3.0));
  const handleZoomOut = () => setScale((prev) => Math.max(prev - 0.2, 0.5));

  const jumpToPage = (targetPage) => {
    if (!numPages) return;
    const pageIdx = Math.max(0, Math.min(targetPage - 1, numPages - 1));
    const targetElement = pageRefs.current[pageIdx];
    if (targetElement) {
      targetElement.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handlePageSubmit = (e) => {
    if (e) e.preventDefault();
    const val = parseInt(pageInputValue);
    if (!isNaN(val) && val > 0 && val <= numPages) {
      jumpToPage(val);
    } else {
      // Revert to current valid page if input is invalid
      setPageInputValue(pageNum.toString());
    }
  };

  // Synchronize current page number with scroll position
  useEffect(() => {
    if (numPages === 0 || loading) return;

    // Small delay to let the DOM settle and prevent premature intersection triggers
    const timer = setTimeout(() => {
      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting) {
              const index = parseInt(entry.target.getAttribute('data-page-index'));
              const newPage = index + 1;
              setPageNum(newPage);
              setPageInputValue(newPage.toString());
            }
          });
        },
        {
          root: scrollContainerRef.current,
          threshold: 0.5, // Require 50% visibility for a page to be considered 'current'
        }
      );

      const currentRefs = pageRefs.current;
      currentRefs.forEach((ref) => {
        if (ref) observer.observe(ref);
      });

      return () => {
        currentRefs.forEach((ref) => {
          if (ref) observer.unobserve(ref);
        });
      };
    }, 100);

    return () => clearTimeout(timer);
  }, [numPages, loading]);

  return (
    <div className="pdf-viewer-container">
      {/* PDF Toolbar */}
      <div className="pdf-toolbar">
        <div className="toolbar-left">
          <button 
            className="toolbar-btn" 
            onClick={() => jumpToPage(pageNum - 1)} 
            disabled={pageNum <= 1 || loading}
          >
            <ChevronLeft size={18} />
          </button>
          
          <form className="page-entry-form" onSubmit={handlePageSubmit}>
            <input 
              type="text" 
              value={pageInputValue} 
              onChange={(e) => setPageInputValue(e.target.value)}
              onBlur={() => {
                if (!pageInputValue) setPageInputValue(pageNum.toString());
                else handlePageSubmit();
              }}
              disabled={loading}
              className="page-entry-input"
            />
            <span className="page-total">/ {numPages || '--'}</span>
          </form>
          
          <button 
            className="toolbar-btn" 
            onClick={() => jumpToPage(pageNum + 1)} 
            disabled={pageNum >= numPages || loading}
          >
            <ChevronRight size={18} />
          </button>
        </div>

        <div className="toolbar-center">
          <button className="toolbar-btn" onClick={handleZoomOut} disabled={loading} title="Zoom Out">
            <ZoomOut size={18} />
          </button>
          <span className="zoom-level">{Math.round(scale * 100)}%</span>
          <button className="toolbar-btn" onClick={handleZoomIn} disabled={loading} title="Zoom In">
            <ZoomIn size={18} />
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="pdf-scroll-container" ref={scrollContainerRef}>
        {error ? (
          <div className="pdf-error">
            <p>{error}</p>
          </div>
        ) : (
          <Document
            file={url}
            onLoadSuccess={onDocumentLoadSuccess}
            onLoadError={onDocumentLoadError}
            loading={
              <div className="pdf-loader">
                <Loader2 className="animate-spin" size={32} />
                <p>Loading PDF...</p>
              </div>
            }
            className="pdf-document"
          >
            {Array.from({ length: numPages }, (_, index) => (
              <div 
                key={`page_\${index + 1}`} 
                className="pdf-page-wrapper" 
                data-page-index={index}
                ref={(el) => (pageRefs.current[index] = el)}
              >
                <Page 
                  pageNumber={index + 1} 
                  scale={scale}
                  renderAnnotationLayer={true}
                  renderTextLayer={true}
                  className="react-pdf__Page"
                  loading={null}
                />
                <div className="page-label">Page {index + 1}</div>
              </div>
            ))}
          </Document>
        )}
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .pdf-viewer-container {
          height: 100%;
          display: flex;
          flex-direction: column;
          background: #525659;
          position: relative;
        }
        .pdf-toolbar {
          height: 48px;
          background: #323639;
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0 16px;
          color: white;
          z-index: 10;
          box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        }
        .toolbar-left, .toolbar-center {
          display: flex;
          align-items: center;
          gap: 12px;
        }
        .toolbar-btn {
          background: transparent;
          border: none;
          color: #eee;
          cursor: pointer;
          width: 32px;
          height: 32px;
          border-radius: 4px;
          display: flex;
          align-items: center;
          justify-content: center;
          transition: background 0.2s;
        }
        .toolbar-btn:hover:not(:disabled) {
          background: rgba(255,255,255,0.1);
        }
        .toolbar-btn:disabled {
          opacity: 0.3;
          cursor: default;
        }
        
        .page-entry-form {
          display: flex;
          align-items: center;
          gap: 8px;
          background: #1a1c1e;
          padding: 2px 8px;
          border-radius: 6px;
          border: 1px solid #444;
        }
        .page-entry-input {
          width: 40px;
          background: transparent;
          border: none;
          color: white;
          text-align: center;
          font-size: 14px;
          outline: none;
        }
        .page-total {
          font-size: 13px;
          color: #888;
        }

        .zoom-level {
          font-size: 13px;
          min-width: 40px;
          text-align: center;
        }

        .pdf-scroll-container {
          flex: 1;
          overflow: auto;
          padding: 30px;
          display: flex;
          flex-direction: column;
          align-items: center;
        }
        .pdf-document {
          display: flex;
          flex-direction: column;
          gap: 30px;
          align-items: center;
        }
        .pdf-page-wrapper {
          position: relative;
          box-shadow: 0 8px 24px rgba(0,0,0,0.4);
          background: white;
        }
        .page-label {
          position: absolute;
          bottom: -22px;
          left: 50%;
          transform: translateX(-50%);
          font-size: 11px;
          font-weight: 600;
          color: #aaa;
          text-transform: uppercase;
          letter-spacing: 1px;
        }

        .pdf-loader, .pdf-error {
          padding: 60px;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          color: #eee;
          gap: 16px;
          text-align: center;
        }
        .retry-btn {
          padding: 10px 24px;
          background: #3498db;
          border: none;
          color: white;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 600;
        }

        .animate-spin {
          animation: spin 1s linear infinite;
        }
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }

        /* react-pdf custom styles */
        .react-pdf__Page__canvas {
          margin: 0 auto;
          display: block !important;
        }
        .react-pdf__Document {
          width: 100%;
          display: flex;
          flex-direction: column;
          align-items: center;
        }
      `}} />
    </div>
  );
};

export default PdfViewer;
